version: "3"

services:
  front:
    stdin_open: true
    restart: always
    container_name: front
    build:
      context: ./front/
    command: yarn start
    volumes:
      - ./front/:/app/front
      - /app/front/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
