version: "3"

services:
  redis:
    restart: always
    image: redis:latest
    command: redis-server --appendonly yes
    container_name: redis
    ports:
      - "6379:6379"
    # volumes:
    #   - ./app/data:/redis
  back:
    restart: always
    container_name: back
    environment:
      BACK_PORT: 5000
      REDIS_URL: redis://redis
    build:
      context: ./back/
    command: yarn dev
    depends_on:
      - redis
    volumes:
      - ./back/:/app/back
      - /app/back/node_modules
    ports:
      - "5000:5000"
  front:
    stdin_open: true
    restart: always
    container_name: front
    depends_on:
      - back
    build:
      context: ./front/
    command: yarn start
    volumes:
      - ./front/:/app/front
      - /app/front/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
